import type { BaseCtx } from "./index";

type FakeResult<Value = unknown, Ctx = unknown> = { value: Value; ctx: Ctx };

export type Pipe<T> = (
	input: any,
	context: any
) => T extends PromiseLike<unknown> ? T : Promise<T>;

export type Fn<Prev, Next, PrevCtx, NextCtx = PrevCtx> = (
	input: Awaited<Prev>,
	context: PrevCtx
) => Next extends FakeResult ? never : Next | FakeResult<Next, NextCtx>;

export function pipe<A, B, C, CA = BaseCtx, CB = CA, CC = CB>(a: Fn<A, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>): Pipe<C>; // prettier-ignore
export function pipe<A, B, C, D, CA = BaseCtx, CB = CA, CC = CB, CD = CC>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>): Pipe<D>; // prettier-ignore
export function pipe<A, B, C, D, E, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>): Pipe<E>; // prettier-ignore
export function pipe<A, B, C, D, E, F, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>): Pipe<F>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>): Pipe<G>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>): Pipe<H>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>): Pipe<I>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>): Pipe<J>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>): Pipe<K>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>): Pipe<L>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>): Pipe<M>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>): Pipe<N>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>): Pipe<O>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>): Pipe<P>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>): Pipe<Q>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>): Pipe<R>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>): Pipe<S>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>): Pipe<T>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>): Pipe<U>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT, CV = CU>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>, u: Fn<Awaited<U>, V, CU, CV>): Pipe<V>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT, CV = CU, CW = CV>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>, u: Fn<Awaited<U>, V, CU, CV>, v: Fn<Awaited<V>, W, CV, CW>): Pipe<W>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT, CV = CU, CW = CV, CX = CW>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>, u: Fn<Awaited<U>, V, CU, CV>, v: Fn<Awaited<V>, W, CV, CW>, w: Fn<Awaited<W>, X, CW, CX>): Pipe<X>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT, CV = CU, CW = CV, CX = CW, CY = CX>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>, u: Fn<Awaited<U>, V, CU, CV>, v: Fn<Awaited<V>, W, CV, CW>, w: Fn<Awaited<W>, X, CW, CX>, x: Fn<Awaited<X>, Y, CX, CY>): Pipe<Y>; // prettier-ignore
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, CA = BaseCtx, CB = CA, CC = CB, CD = CC, CE = CD, CF = CE, CG = CF, CH = CG, CI = CH, CJ = CI, CK = CJ, CL = CK, CM = CL, CN = CM, CO = CN, CP = CO, CQ = CP, CR = CQ, CS = CR, CT = CS, CU = CT, CV = CU, CW = CV, CX = CW, CY = CX, CZ = CY>(a: Fn<Awaited<A>, B, CA, CB>, b: Fn<Awaited<B>, C, CB, CC>, c: Fn<Awaited<C>, D, CC, CD>, d: Fn<Awaited<D>, E, CD, CE>, e: Fn<Awaited<E>, F, CE, CF>, f: Fn<Awaited<F>, G, CF, CG>, g: Fn<Awaited<G>, H, CG, CH>, h: Fn<Awaited<H>, I, CH, CI>, i: Fn<Awaited<I>, J, CI, CJ>, j: Fn<Awaited<J>, K, CJ, CK>, k: Fn<Awaited<K>, L, CK, CL>, l: Fn<Awaited<L>, M, CL, CM>, m: Fn<Awaited<M>, N, CM, CN>, n: Fn<Awaited<N>, O, CN, CO>, o: Fn<Awaited<O>, P, CO, CP>, p: Fn<Awaited<P>, Q, CP, CQ>, q: Fn<Awaited<Q>, R, CQ, CR>, r: Fn<Awaited<R>, S, CR, CS>, s: Fn<Awaited<S>, T, CS, CT>, t: Fn<Awaited<T>, U, CT, CU>, u: Fn<Awaited<U>, V, CU, CV>, v: Fn<Awaited<V>, W, CV, CW>, w: Fn<Awaited<W>, X, CW, CX>, x: Fn<Awaited<X>, Y, CX, CY>, y: Fn<Awaited<Y>, Z, CY, CZ>): Pipe<Z>; // prettier-ignore

export function pipe(...functions: unknown[]) {
	const fns = functions as Fn<unknown, unknown, unknown, unknown>[];

	return async (input: any, context: any) => {
		let lastResult = input;

		for (const fn of fns) {
			lastResult = await fn(lastResult, context);

			if (lastResult instanceof Response) {
				return lastResult;
			}
		}

		return lastResult;
	};
}
